// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: kvmesh.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Prompt      string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	MaxTokens   int32                  `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// We can add a unique request ID for tracing
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_kvmesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvmesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_kvmesh_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *GenerateRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenerateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IsFinished    bool                   `protobuf:"varint,2,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_kvmesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvmesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_kvmesh_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GenerateResponse) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

type HeartbeatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerId        string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	GrpcAddress     string                 `protobuf:"bytes,2,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`               // How the gateway can reach this worker
	VramUtilization float32                `protobuf:"fixed32,3,opt,name=vram_utilization,json=vramUtilization,proto3" json:"vram_utilization,omitempty"` // e.g., 0.85 for 85% full
	// For Phase 2: We will send hashed prefixes of what currently lives in this worker's KV Cache
	CachedPrefixes []uint64 `protobuf:"varint,4,rep,packed,name=cached_prefixes,json=cachedPrefixes,proto3" json:"cached_prefixes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_kvmesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvmesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_kvmesh_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

func (x *HeartbeatRequest) GetVramUtilization() float32 {
	if x != nil {
		return x.VramUtilization
	}
	return 0
}

func (x *HeartbeatRequest) GetCachedPrefixes() []uint64 {
	if x != nil {
		return x.CachedPrefixes
	}
	return nil
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_kvmesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_kvmesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_kvmesh_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_kvmesh_proto protoreflect.FileDescriptor

const file_kvmesh_proto_rawDesc = "" +
	"\n" +
	"\fkvmesh.proto\x12\x06kvmesh\"\x89\x01\n" +
	"\x0fGenerateRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"G\n" +
	"\x10GenerateResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\vis_finished\x18\x02 \x01(\bR\n" +
	"isFinished\"\xa6\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12!\n" +
	"\fgrpc_address\x18\x02 \x01(\tR\vgrpcAddress\x12)\n" +
	"\x10vram_utilization\x18\x03 \x01(\x02R\x0fvramUtilization\x12'\n" +
	"\x0fcached_prefixes\x18\x04 \x03(\x04R\x0ecachedPrefixes\"(\n" +
	"\fHeartbeatAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2S\n" +
	"\n" +
	"WorkerNode\x12E\n" +
	"\x0eGenerateStream\x12\x17.kvmesh.GenerateRequest\x1a\x18.kvmesh.GenerateResponse0\x012N\n" +
	"\vGatewayNode\x12?\n" +
	"\rSendHeartbeat\x12\x18.kvmesh.HeartbeatRequest\x1a\x14.kvmesh.HeartbeatAckB\x14Z\x12kv-mesh/gateway/pbb\x06proto3"

var (
	file_kvmesh_proto_rawDescOnce sync.Once
	file_kvmesh_proto_rawDescData []byte
)

func file_kvmesh_proto_rawDescGZIP() []byte {
	file_kvmesh_proto_rawDescOnce.Do(func() {
		file_kvmesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kvmesh_proto_rawDesc), len(file_kvmesh_proto_rawDesc)))
	})
	return file_kvmesh_proto_rawDescData
}

var file_kvmesh_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kvmesh_proto_goTypes = []any{
	(*GenerateRequest)(nil),  // 0: kvmesh.GenerateRequest
	(*GenerateResponse)(nil), // 1: kvmesh.GenerateResponse
	(*HeartbeatRequest)(nil), // 2: kvmesh.HeartbeatRequest
	(*HeartbeatAck)(nil),     // 3: kvmesh.HeartbeatAck
}
var file_kvmesh_proto_depIdxs = []int32{
	0, // 0: kvmesh.WorkerNode.GenerateStream:input_type -> kvmesh.GenerateRequest
	2, // 1: kvmesh.GatewayNode.SendHeartbeat:input_type -> kvmesh.HeartbeatRequest
	1, // 2: kvmesh.WorkerNode.GenerateStream:output_type -> kvmesh.GenerateResponse
	3, // 3: kvmesh.GatewayNode.SendHeartbeat:output_type -> kvmesh.HeartbeatAck
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kvmesh_proto_init() }
func file_kvmesh_proto_init() {
	if File_kvmesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvmesh_proto_rawDesc), len(file_kvmesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_kvmesh_proto_goTypes,
		DependencyIndexes: file_kvmesh_proto_depIdxs,
		MessageInfos:      file_kvmesh_proto_msgTypes,
	}.Build()
	File_kvmesh_proto = out.File
	file_kvmesh_proto_goTypes = nil
	file_kvmesh_proto_depIdxs = nil
}
