// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: kvmesh.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerNode_GenerateStream_FullMethodName = "/kvmesh.WorkerNode/GenerateStream"
)

// WorkerNodeClient is the client API for WorkerNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service exposed by the Python Worker node to the Go Gateway
type WorkerNodeClient interface {
	// Standard generation request, streams tokens back
	GenerateStream(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error)
}

type workerNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerNodeClient(cc grpc.ClientConnInterface) WorkerNodeClient {
	return &workerNodeClient{cc}
}

func (c *workerNodeClient) GenerateStream(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerNode_ServiceDesc.Streams[0], WorkerNode_GenerateStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GenerateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerNode_GenerateStreamClient = grpc.ServerStreamingClient[GenerateResponse]

// WorkerNodeServer is the server API for WorkerNode service.
// All implementations must embed UnimplementedWorkerNodeServer
// for forward compatibility.
//
// The service exposed by the Python Worker node to the Go Gateway
type WorkerNodeServer interface {
	// Standard generation request, streams tokens back
	GenerateStream(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error
	mustEmbedUnimplementedWorkerNodeServer()
}

// UnimplementedWorkerNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerNodeServer struct{}

func (UnimplementedWorkerNodeServer) GenerateStream(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error {
	return status.Error(codes.Unimplemented, "method GenerateStream not implemented")
}
func (UnimplementedWorkerNodeServer) mustEmbedUnimplementedWorkerNodeServer() {}
func (UnimplementedWorkerNodeServer) testEmbeddedByValue()                    {}

// UnsafeWorkerNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerNodeServer will
// result in compilation errors.
type UnsafeWorkerNodeServer interface {
	mustEmbedUnimplementedWorkerNodeServer()
}

func RegisterWorkerNodeServer(s grpc.ServiceRegistrar, srv WorkerNodeServer) {
	// If the following call panics, it indicates UnimplementedWorkerNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerNode_ServiceDesc, srv)
}

func _WorkerNode_GenerateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerNodeServer).GenerateStream(m, &grpc.GenericServerStream[GenerateRequest, GenerateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerNode_GenerateStreamServer = grpc.ServerStreamingServer[GenerateResponse]

// WorkerNode_ServiceDesc is the grpc.ServiceDesc for WorkerNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kvmesh.WorkerNode",
	HandlerType: (*WorkerNodeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateStream",
			Handler:       _WorkerNode_GenerateStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kvmesh.proto",
}

const (
	GatewayNode_SendHeartbeat_FullMethodName = "/kvmesh.GatewayNode/SendHeartbeat"
)

// GatewayNodeClient is the client API for GatewayNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service exposed by the Go Gateway to collect telemetry from Workers
type GatewayNodeClient interface {
	// Workers periodically send heartbeats with their KV cache state and VRAM load
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatAck, error)
}

type gatewayNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayNodeClient(cc grpc.ClientConnInterface) GatewayNodeClient {
	return &gatewayNodeClient{cc}
}

func (c *gatewayNodeClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatAck)
	err := c.cc.Invoke(ctx, GatewayNode_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayNodeServer is the server API for GatewayNode service.
// All implementations must embed UnimplementedGatewayNodeServer
// for forward compatibility.
//
// The service exposed by the Go Gateway to collect telemetry from Workers
type GatewayNodeServer interface {
	// Workers periodically send heartbeats with their KV cache state and VRAM load
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatAck, error)
	mustEmbedUnimplementedGatewayNodeServer()
}

// UnimplementedGatewayNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayNodeServer struct{}

func (UnimplementedGatewayNodeServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedGatewayNodeServer) mustEmbedUnimplementedGatewayNodeServer() {}
func (UnimplementedGatewayNodeServer) testEmbeddedByValue()                     {}

// UnsafeGatewayNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayNodeServer will
// result in compilation errors.
type UnsafeGatewayNodeServer interface {
	mustEmbedUnimplementedGatewayNodeServer()
}

func RegisterGatewayNodeServer(s grpc.ServiceRegistrar, srv GatewayNodeServer) {
	// If the following call panics, it indicates UnimplementedGatewayNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayNode_ServiceDesc, srv)
}

func _GatewayNode_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNodeServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayNode_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNodeServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayNode_ServiceDesc is the grpc.ServiceDesc for GatewayNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kvmesh.GatewayNode",
	HandlerType: (*GatewayNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHeartbeat",
			Handler:    _GatewayNode_SendHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kvmesh.proto",
}
