# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import kvmesh_pb2 as kvmesh__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kvmesh_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerNodeStub:
    """The service exposed by the Python Worker node to the Go Gateway
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateStream = channel.unary_stream(
                '/kvmesh.WorkerNode/GenerateStream',
                request_serializer=kvmesh__pb2.GenerateRequest.SerializeToString,
                response_deserializer=kvmesh__pb2.GenerateResponse.FromString,
                _registered_method=True)


class WorkerNodeServicer:
    """The service exposed by the Python Worker node to the Go Gateway
    """

    def GenerateStream(self, request, context):
        """Standard generation request, streams tokens back
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateStream,
                    request_deserializer=kvmesh__pb2.GenerateRequest.FromString,
                    response_serializer=kvmesh__pb2.GenerateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvmesh.WorkerNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvmesh.WorkerNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerNode:
    """The service exposed by the Python Worker node to the Go Gateway
    """

    @staticmethod
    def GenerateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kvmesh.WorkerNode/GenerateStream',
            kvmesh__pb2.GenerateRequest.SerializeToString,
            kvmesh__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GatewayNodeStub:
    """The service exposed by the Go Gateway to collect telemetry from Workers
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendHeartbeat = channel.unary_unary(
                '/kvmesh.GatewayNode/SendHeartbeat',
                request_serializer=kvmesh__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=kvmesh__pb2.HeartbeatAck.FromString,
                _registered_method=True)


class GatewayNodeServicer:
    """The service exposed by the Go Gateway to collect telemetry from Workers
    """

    def SendHeartbeat(self, request, context):
        """Workers periodically send heartbeats with their KV cache state and VRAM load
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=kvmesh__pb2.HeartbeatRequest.FromString,
                    response_serializer=kvmesh__pb2.HeartbeatAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvmesh.GatewayNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvmesh.GatewayNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayNode:
    """The service exposed by the Go Gateway to collect telemetry from Workers
    """

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvmesh.GatewayNode/SendHeartbeat',
            kvmesh__pb2.HeartbeatRequest.SerializeToString,
            kvmesh__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
